plugins:
  - bsmu.vision.plugins.file_dropper.FileDropperPlugin
  - bsmu.vision.plugins.loaders.image.simple.SimpleImageFileLoaderPlugin
  - bsmu.vision.plugins.visualizers.image.flat.FlatImageVisualizerPlugin
  - bsmu.bone_age.plugins.analyzer.BoneAgeAnalyzerPlugin
